### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by philip** [UnicornGlobal/strong-lumen#7]
Request: instructions for installing and setting this up.

**Comment by dels07** [comment]
+1, especially with public and private key and how to handle app_id both in frontend and backend

**Comment by akahen** [comment]
same, trying to get app id working... yet keeps saying not auth. also any other route besides home fails to even return anything, even above the first group route

**Comment by fergusdixon** [comment]
Please see https://github.com/UnicornGlobal/strong-lumen#app-id for App ID instructions 

Every route with `appid` middleware requires the `App: {uuid}` header. 

Any route within the `/api` group requires you to log in first, and have header `Authorization: Bearer {jwt}` on all future requests.

See https://github.com/UnicornGlobal/strong-lumen#jwt for instructions on the private and public keys.

@philip @dels07 @akahen
